# -*- coding: utf-8 -*-
"""RAG PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16V5hgOsTausUAZIZfmo1IewL4I_KdaAb
"""

!pip install chromadb sentence-transformers google-generativeai langchain \
             langchain-community langchain-text-splitters pypdf streamlit pyngrok pandas -q

import chromadb
import sentence_transformers
import google.generativeai as genai
import langchain
import streamlit
import pyngrok

print("chromadb:", chromadb.__version__)
print("sentence-transformers:", sentence_transformers.__version__)
print("google-generativeai imported ✅")
print("All libraries working!")

from google.colab import drive
drive.mount('/content/drive')

import os

BASE = '/content/drive/MyDrive/RAG PROJECT'
DOCS_PATH = f'{BASE}/docs'
DB_PATH = f'{BASE}/chroma_db'
APP_PATH = f'{BASE}/app.py'

os.makedirs(BASE, exist_ok=True)
os.makedirs(DOCS_PATH, exist_ok=True)
os.makedirs(DB_PATH, exist_ok=True)

print("Drive mounted. Folders ready.")
print("BASE:", BASE)
print("DOCS_PATH:", DOCS_PATH)
print("DB_PATH:", DB_PATH)
print("Current contents of BASE:", os.listdir(BASE))

from textwrap import dedent
import os

product_manual_text = dedent("""
Product 1: TL-COLD-9001 (CryoVial Injectable Solution)
- Category: Cold Chain Pharmaceutical
- Storage: 2°C to 8°C, below 60% RH, dark conditions
- Shelf life: 24 months
- Packaging: 5ml vial, 10 vials/carton, 50 cartons/case, 12.5kg
- Rules: Do not freeze. Discard if >10°C for more than 2 hours.
- Supplier: MedSupply India Pvt Ltd, Pune

Product 2: TL-DRY-4402 (StableCap Dry Powder)
- Category: Ambient Temperature Pharmaceutical
- Storage: 15°C to 25°C, below 45% RH
- Shelf life: 36 months
- Packaging: 100g sealed pouch, 20 pouches/carton, 8kg
- Rules: Keep away from moisture. Silica gel in each case.

Product 3: TL-FROZ-7700 (FreezeGuard Biological Sample Kit)
- Category: Frozen Pharmaceutical/Biological
- Storage: -20°C or below
- Shelf life: 18 months
- Packaging: 2ml cryotube, 5 cryotubes/pack, 100 packs/insulated case
- Rules: Use dry ice for transport. Do not refreeze once thawed.

General: All products WHO-GMP certified, Schedule M compliant.
Contact: quality@tracelink-biomed.com for CoA requests.
""").strip()

compliance_guide_text = dedent("""
Section 1 - Shipment Documentation:
- All shipments need signed Delivery Order before dispatch
- Shipment log must be updated in system within 24 hours of dispatch
- Each shipment must include: Invoice, CoA, temperature log, batch/expiry info
- Temperature data loggers must be activated at origin before loading
- Driver must sign Cold Chain Handover Form for refrigerated shipments

Section 2 - Temperature Monitoring Rules:
- Cold chain (2-8°C): if >10°C at any point → quarantine immediately,
  notify QA within 2 hours, cannot release without investigation
- Frozen (<-20°C): if rises above -10°C → automatically rejected,
  destruction record within 48 hours
- Ambient (15-25°C): if >30°C for 4+ continuous hours → report to
  supervisor, QA issues deviation report
- All temperature loggers must be calibrated every 6 months

Section 3 - Warehouse Compliance:
- Cold storage units validated annually (IQ/OQ/PQ)
- Pest control monthly, physical inventory quarterly
- FIFO mandatory for all storage
- Rejected/expired stock in segregated quarantine area labeled DO NOT USE
- All warehouse staff complete GDP training annually

Section 4 - Shipment Delay Protocol:
- Delay >48 hours: QA must reassess product integrity
- Delayed cold chain: temperature logs reviewed before acceptance
- Customer notified of any delay exceeding 24 hours

Section 5 - Returns and Recalls:
- Returns accepted within 30 days of delivery only
- Returned products quarantined, cannot restock without QA approval
- Recall procedure: identify affected batches within 4 hours, retrieve
  distribution list, notify CDSCO within 72 hours

Section 6 - Penalties:
- Shipment log not updated within 24h: Warning + Rs.5000 penalty
- Releasing product without QA clearance after breach: Suspend license
- Falsification of temperature records: Termination + legal action
""").strip()

shipment_log_text = dedent("""
SH-2024-001: TL-COLD-9001, Batch BATCH-CRY-2401, 200 vials
  Pune → Apollo Hospital Mumbai | Jan 10-11 | DELIVERED
  Temp: 3.1°C min, 6.8°C max | No breach | Accepted by Ramesh Kulkarni

SH-2024-002: TL-DRY-4402, Batch BATCH-DRY-2402, 500 pouches
  Pune → Medline Distributor Nashik | Jan 18-19 | DELIVERED
  Temp: 22°C ambient | No breach | Accepted by Priya Shah

SH-2024-003: TL-COLD-9001, Batch BATCH-CRY-2401, 150 vials
  Pune → Fortis Hospital Hyderabad | Feb 5-7 | QUARANTINED
  Temp: 3.5°C min, 11.2°C max | BREACH: exceeded 10°C for 3 hours
  Action: Quarantined, deviation report DEV-2024-003, QA investigation

SH-2024-004: TL-FROZ-7700, Batch BATCH-FRZ-2403, 80 packs
  Pune → GenPath Lab Bangalore | Feb 14-15 | DELIVERED
  Temp: -22°C min, -18°C max | No breach | Accepted by Dr. Anita Rao

SH-2024-005: TL-DRY-4402, Batch BATCH-DRY-2404, 1000 pouches
  Pune → PharmaPlus Delhi | Mar 1-4 | DELAYED (truck breakdown, 3 days)
  Temp: 24°C ambient | No breach | QA reassessment done, approved
  Accepted by Sandeep Arora

SH-2024-006: TL-COLD-9001, Batch BATCH-CRY-2405, 300 vials
  Pune → Cipla Hub Chennai | Mar 20-21 | DELIVERED
  Temp: 2.9°C min, 7.4°C max | No breach | Accepted by Kavitha Nair

SH-2024-007: TL-FROZ-7700, Batch BATCH-FRZ-2403, 40 packs
  Pune → SciLab Research Kolkata | Apr 8-9 | REJECTED
  Temp: -19°C min, -8°C max | BREACH: rose above -10°C during transit
  Action: Full batch rejected, destruction record DES-2024-007,
          CDSCO notified

Summary: 7 total | 4 delivered | 1 quarantined | 1 rejected | 1 delayed
Temperature breach rate: 28.5%
""").strip()

documents = {
    "product_manual.txt": product_manual_text,
    "compliance_guide.txt": compliance_guide_text,
    "shipment_log.txt": shipment_log_text,
}

for filename, content in documents.items():
    file_path = os.path.join(DOCS_PATH, filename)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content + "\n")
    print(f"Saved: {file_path} | {len(content)} characters")

print("\nAll mock documents written successfully.")
print("docs/ folder contents:", sorted(os.listdir(DOCS_PATH)))

import os

files = sorted(os.listdir(DOCS_PATH))
print(f"Found {len(files)} files in docs/: {files}\n")

for filename in files:
    file_path = os.path.join(DOCS_PATH, filename)
    with open(file_path, "r", encoding="utf-8") as f:
        text = f.read()

    print("=" * 80)
    print("FILE:", filename)
    print("SIZE:", len(text), "characters")
    print("PREVIEW:")
    print(text[:300])
    print()

required_files = {
    "product_manual.txt",
    "compliance_guide.txt",
    "shipment_log.txt",
}

existing_files = set(os.listdir(DOCS_PATH))
missing_files = required_files - existing_files

print("BASE exists:", os.path.exists(BASE))
print("DOCS_PATH exists:", os.path.exists(DOCS_PATH))
print("DB_PATH exists:", os.path.exists(DB_PATH))

if not missing_files:
    print("\n✅ DAY 1 COMPLETE")
    print("All required mock documents are present in:", DOCS_PATH)
    print("Ready for Day 2 ingestion pipeline.")
else:
    print("\n❌ DAY 1 NOT COMPLETE")
    print("Missing files:", missing_files)

"""## DAY 2"""

# ==========================================================
# CELL 1 — TASK 1: WRITE 5 IMPROVED DOCUMENTS TO DRIVE
# Purpose: Richer pharma supply-chain content, structured for
#          clean section-aware chunking (=== headers).
# ==========================================================
import os, time

BASE      = '/content/drive/MyDrive/RAG PROJECT'
DOCS_PATH = f'{BASE}/docs'
DB_PATH   = f'{BASE}/chroma_db'
APP_PATH  = f'{BASE}/app.py'

try:
    os.makedirs(DOCS_PATH, exist_ok=True)
    print(f"📁 docs folder ready: {DOCS_PATH}")
except Exception as e:
    raise RuntimeError(f"❌ Could not create docs folder: {e}")

# ---------- FILE 1: product_manual.txt ----------
product_manual = """=== PRODUCT MANUAL — TRACELINK BIOMED ===
Document ID: DOC-PM-2024 | Version: 3.1 | Effective: 01-Jan-2024
All products WHO-GMP certified and Schedule M compliant.
Quality contact: quality@tracelink-biomed.com | +91-20-4000-1100

=== PRODUCT TL-COLD-9001 — CryoVial Injectable Solution ===
Product code: TL-COLD-9001
Trade name: CryoVial Injectable Solution
Category: Cold Chain Pharmaceutical (Schedule H)
Manufacturer: TraceLink BioMed Pvt Ltd, Pune
Primary supplier: MedSupply India Pvt Ltd, Pune
Storage condition: 2°C to 8°C, below 60% relative humidity, dark conditions
Shelf life: 24 months from date of manufacture
Packaging: 5 ml glass vial | 10 vials per carton | 50 cartons per case | gross weight 12.5 kg
Excursion rule: Discard if exposed above 10°C for more than 2 continuous hours.
Handling rule: Do not freeze. Once removed from refrigeration, use within 6 hours.
Transport: Validated cold box with PCM packs and a calibrated data logger per case.

=== PRODUCT TL-DRY-4402 — StableCap Dry Powder ===
Product code: TL-DRY-4402
Trade name: StableCap Dry Powder
Category: Ambient Temperature Pharmaceutical
Manufacturer: TraceLink BioMed Pvt Ltd, Pune
Primary supplier: Deccan Pharma Logistics, Pune
Storage condition: 15°C to 25°C, below 45% relative humidity
Shelf life: 36 months from date of manufacture
Packaging: 100 g sealed pouch | 20 pouches per carton | 8 kg per case
Excursion rule: Report if above 30°C for 4 or more continuous hours.
Handling rule: Keep away from moisture. Silica gel sachet included. Do not open until point of use.

=== PRODUCT TL-FROZ-7700 — FreezeGuard Biological Sample Kit ===
Product code: TL-FROZ-7700
Trade name: FreezeGuard Biological Sample Kit
Category: Frozen Pharmaceutical / Biological
Manufacturer: TraceLink BioMed Pvt Ltd, Pune
Primary supplier: ArcticLine Cold Logistics, Mumbai
Storage condition: -20°C or below
Shelf life: 18 months from date of manufacture
Packaging: 2 ml cryotube | 5 tubes per pack | 100 packs per insulated case
Excursion rule: Automatically rejected if temperature rises above -10°C.
Handling rule: Transport on dry ice only. Never use regular ice. Do not refreeze once thawed.

=== PRODUCT TL-COLD-9015 — ImmunoChill Vaccine Vials ===
Product code: TL-COLD-9015
Trade name: ImmunoChill Vaccine Vials
Category: Cold Chain Pharmaceutical (Vaccine)
Manufacturer: TraceLink BioMed Pvt Ltd, Pune
Primary supplier: MedSupply India Pvt Ltd, Pune
Storage condition: 2°C to 8°C, protect from light, do not freeze
Shelf life: 12 months from date of manufacture
Packaging: 0.5 ml vial | 20 vials per carton | 40 cartons per case
Excursion rule: Discard if frozen at any point, or if above 8°C cumulatively for more than 12 hours.
Handling rule: Vaccine Vial Monitor (VVM) must be checked at every handover.

=== PRODUCT TL-DRY-4410 — OralRehydrate Sachets ===
Product code: TL-DRY-4410
Trade name: OralRehydrate Sachets
Category: Ambient Temperature Pharmaceutical (OTC)
Manufacturer: TraceLink BioMed Pvt Ltd, Pune
Primary supplier: Deccan Pharma Logistics, Pune
Storage condition: below 30°C, dry place
Shelf life: 30 months from date of manufacture
Packaging: 21 g sachet | 50 sachets per box | 24 boxes per case
Excursion rule: No cold chain required; protect from direct sunlight and moisture.
Handling rule: Stack maximum 8 cases high to avoid pouch crushing.
"""

# ---------- FILE 2: compliance_guide.txt ----------
compliance_guide = """=== GDP COMPLIANCE GUIDE — TRACELINK BIOMED ===
Document ID: DOC-CG-2024 | Version: 4.0 | Based on WHO GDP and CDSCO guidelines.

=== SECTION 1 — SHIPMENT DOCUMENTATION ===
A signed Delivery Order is mandatory before any dispatch.
The shipment log must be updated within 24 hours of dispatch.
Every shipment must include: tax Invoice, Certificate of Analysis (CoA), temperature log, and batch/expiry information.
Temperature data loggers must be activated at origin before loading.
For refrigerated items the driver must sign the Cold Chain Handover Form.
A Delivery Order without QA sign-off is treated as void.

=== SECTION 2 — TEMPERATURE MONITORING ===
Cold chain products (2-8°C): if temperature exceeds 10°C at any point, quarantine immediately, notify QA within 2 hours, and do not release until the QA investigation is complete.
Frozen products (-20°C or below): if temperature rises above -10°C, the consignment is automatically rejected and a destruction record must be raised within 48 hours.
Ambient products (15-25°C): if temperature exceeds 30°C for 4 or more continuous hours, report to the warehouse supervisor and QA issues a deviation report.
All temperature loggers must be calibrated every 6 months by an accredited lab.
Logger calibration certificates are retained for 3 years.

=== SECTION 3 — WAREHOUSE COMPLIANCE ===
Cold storage units are validated annually using IQ, OQ, and PQ protocols.
Pest control is performed monthly; inventory reconciliation is performed quarterly.
FIFO (First In First Out) is mandatory for all product storage.
Rejected or expired stock is moved to a segregated quarantine zone labelled DO NOT USE.
All warehouse staff complete GDP refresher training annually.
Temperature mapping of each cold room is repeated every 2 years.

=== SECTION 4 — SHIPMENT DELAY PROTOCOL ===
For any delay exceeding 48 hours, QA must reassess product integrity before acceptance.
For delayed cold chain shipments, temperature logs must be reviewed before acceptance.
The customer must be notified of any delay exceeding 24 hours.
If a delay is caused by vehicle breakdown, a backup validated vehicle must be dispatched within 6 hours.

=== SECTION 5 — RETURNS AND RECALLS ===
Returns are accepted only within 30 days of delivery.
Returned products are quarantined and cannot be restocked without QA approval.
In a recall, affected batches must be identified within 4 hours.
The distribution list is retrieved from the TraceLink traceability system.
CDSCO must be notified within 72 hours of a confirmed recall.

=== SECTION 6 — PENALTIES ===
Shipment log not updated within 24 hours: Warning plus Rs. 5,000 penalty.
Releasing product without QA clearance after a breach: license suspension.
Falsifying temperature records: termination plus legal action.
Repeated GDP training non-completion: removal from cold chain duties.
"""

# ---------- FILE 3: shipment_log.txt ----------
shipment_log = """=== SHIPMENT LOG FY2024 — TRACELINK BIOMED ===
Document ID: DOC-SL-2024 | All times IST. Origin warehouse: Pune unless noted.

=== SHIPMENT SH-2024-001 ===
Shipment ID: SH-2024-001 | Product: TL-COLD-9001 | Batch: BATCH-CRY-2401 | Quantity: 200 vials
Route: Pune to Apollo Hospital Mumbai | Dates: Jan 10-11 | Status: DELIVERED
Temperature: 3.1°C min / 6.8°C max | No breach
Accepted by: Ramesh Kulkarni (Pharmacy Manager)

=== SHIPMENT SH-2024-002 ===
Shipment ID: SH-2024-002 | Product: TL-DRY-4402 | Batch: BATCH-DRY-2402 | Quantity: 500 pouches
Route: Pune to Medline Distributor Nashik | Dates: Jan 18-19 | Status: DELIVERED
Temperature: 22°C ambient | No breach
Accepted by: Priya Shah

=== SHIPMENT SH-2024-003 ===
Shipment ID: SH-2024-003 | Product: TL-COLD-9001 | Batch: BATCH-CRY-2401 | Quantity: 150 vials
Route: Pune to Fortis Hospital Hyderabad | Dates: Feb 5-7 | Status: QUARANTINED
Temperature: 3.5°C min / 11.2°C max | BREACH: exceeded 10°C for 3 hours
Action: Quarantined | Deviation report DEV-2024-003 raised | Pending QA clearance

=== SHIPMENT SH-2024-004 ===
Shipment ID: SH-2024-004 | Product: TL-FROZ-7700 | Batch: BATCH-FRZ-2403 | Quantity: 80 packs
Route: Pune to GenPath Lab Bangalore | Dates: Feb 14-15 | Status: DELIVERED
Temperature: -22°C min / -18°C max | No breach
Accepted by: Dr. Anita Rao

=== SHIPMENT SH-2024-005 ===
Shipment ID: SH-2024-005 | Product: TL-DRY-4402 | Batch: BATCH-DRY-2404 | Quantity: 1000 pouches
Route: Pune to PharmaPlus Delhi | Dates: Mar 1-4 | Status: DELAYED (truck breakdown)
Delay: 3 days | Temperature: 24°C ambient | No breach
QA reassessment: Done, approved | Accepted by: Sandeep Arora

=== SHIPMENT SH-2024-006 ===
Shipment ID: SH-2024-006 | Product: TL-COLD-9001 | Batch: BATCH-CRY-2405 | Quantity: 300 vials
Route: Pune to Cipla Hub Chennai | Dates: Mar 20-21 | Status: DELIVERED
Temperature: 2.9°C min / 7.4°C max | No breach
Accepted by: Kavitha Nair

=== SHIPMENT SH-2024-007 ===
Shipment ID: SH-2024-007 | Product: TL-FROZ-7700 | Batch: BATCH-FRZ-2403 | Quantity: 40 packs
Route: Pune to SciLab Research Kolkata | Dates: Apr 8-9 | Status: REJECTED
Temperature: -19°C min / -8°C max | BREACH: rose above -10°C
Action: Full batch rejected | Destruction record DES-2024-007 | CDSCO notified

=== SHIPMENT SH-2024-008 ===
Shipment ID: SH-2024-008 | Product: TL-COLD-9015 | Batch: BATCH-VAC-2406 | Quantity: 400 vials
Route: Pune to District Health Office Nagpur | Dates: May 2-3 | Status: DELIVERED
Temperature: 3.0°C min / 7.9°C max | VVM stage 1 | No breach
Accepted by: Dr. Meena Joshi

=== SHIPMENT SH-2024-009 ===
Shipment ID: SH-2024-009 | Product: TL-DRY-4410 | Batch: BATCH-ORS-2407 | Quantity: 60 boxes
Route: Pune to Relief Camp Pune Rural | Dates: Jun 12 | Status: DELIVERED
Temperature: 27°C ambient | No breach
Accepted by: Field Coordinator Vikram Patil

=== SHIPMENT SH-2024-010 ===
Shipment ID: SH-2024-010 | Product: TL-FROZ-7700 | Batch: BATCH-FRZ-2408 | Quantity: 90 packs
Route: Pune to GenPath Lab Bangalore | Dates: Jul 5-6 | Status: DELIVERED
Temperature: -24°C min / -19°C max | No breach
Accepted by: Dr. Anita Rao

=== SHIPMENT LOG SUMMARY FY2024 ===
Total shipments: 10 | Delivered: 7 | Quarantined: 1 | Rejected: 1 | Delayed: 1
Temperature breach count: 2 (SH-2024-003 and SH-2024-007)
Breach rate: 20% (2 out of 10 shipments)
"""

# ---------- FILE 4: vendor_list.txt (NEW) ----------
vendor_list = """=== VENDOR & SUPPLIER LIST — TRACELINK BIOMED ===
Document ID: DOC-VL-2024 | Version: 2.2 | Procurement contact: procurement@tracelink-biomed.com

=== VENDOR V-001 — MedSupply India Pvt Ltd ===
Vendor code: V-001
Name: MedSupply India Pvt Ltd
Location: Pune, Maharashtra
Supplies: TL-COLD-9001, TL-COLD-9015 (cold chain pharmaceuticals)
Contact person: Anil Deshmukh | Phone: +91-20-2550-3300 | Email: anil@medsupply.in
SLA delivery window: 48 hours within Maharashtra, 72 hours outside
On-time delivery rate FY2024: 96%
Quality rating: A (audited Mar-2024)
Cold chain certified: Yes (WHO PQS compliant)

=== VENDOR V-002 — Deccan Pharma Logistics ===
Vendor code: V-002
Name: Deccan Pharma Logistics
Location: Pune, Maharashtra
Supplies: TL-DRY-4402, TL-DRY-4410 (ambient pharmaceuticals)
Contact person: Sunita Rao | Phone: +91-20-2660-7788 | Email: sunita@deccanpharma.in
SLA delivery window: 72 hours nationwide
On-time delivery rate FY2024: 91%
Quality rating: B+ (audited Jan-2024)
Cold chain certified: Not required (ambient only)

=== VENDOR V-003 — ArcticLine Cold Logistics ===
Vendor code: V-003
Name: ArcticLine Cold Logistics
Location: Mumbai, Maharashtra
Supplies: TL-FROZ-7700 (frozen biological)
Contact person: Rohan Mehta | Phone: +91-22-4012-9090 | Email: rohan@arcticline.in
SLA delivery window: 36 hours for dry-ice frozen shipments
On-time delivery rate FY2024: 88%
Quality rating: A- (audited Feb-2024)
Cold chain certified: Yes (dry ice / -20°C specialist)
Note: ArcticLine handled the rejected shipment SH-2024-007; corrective action under review.

=== VENDOR V-004 — SafeMove Transport Services ===
Vendor code: V-004
Name: SafeMove Transport Services
Location: Pune, Maharashtra
Supplies: Last-mile refrigerated transport (all cold chain SKUs)
Contact person: Imran Shaikh | Phone: +91-20-2780-1212 | Email: ops@safemove.in
SLA delivery window: same-day within Pune, next-day within 300 km
On-time delivery rate FY2024: 94%
Quality rating: A (audited Apr-2024)
Cold chain certified: Yes (validated reefer fleet)

=== VENDOR ESCALATION MATRIX ===
Level 1 (delay under 24h): handled by assigned vendor contact person.
Level 2 (delay 24-48h): escalate to TraceLink procurement lead, procurement@tracelink-biomed.com.
Level 3 (delay over 48h or any temperature breach): escalate to QA head, quality@tracelink-biomed.com, plus written deviation.
Any vendor with on-time rate below 90% for two consecutive quarters is placed on a probation review.
"""

# ---------- FILE 5: incident_report_2024.txt (NEW) ----------
incident_report = """=== INCIDENT REPORT FY2024 — TEMPERATURE BREACHES ===
Document ID: DOC-IR-2024 | Version: 1.0 | Prepared by: QA Department, TraceLink BioMed.
Scope: Root cause analysis of the two temperature breaches recorded in FY2024.

=== INCIDENT INC-2024-01 — SH-2024-003 QUARANTINE ===
Related shipment: SH-2024-003 | Product: TL-COLD-9001 | Batch: BATCH-CRY-2401
Event: Cold chain consignment to Fortis Hospital Hyderabad reached 11.2°C, exceeding the 10°C limit for 3 hours.
Detection: Data logger alarm flagged on arrival scan, Feb 7.
Root cause: PCM cold packs were not fully conditioned (frozen) before loading; transit took 4 hours longer than planned due to a highway diversion.
Contributing factor: No backup cold box was available at the transfer point.
Immediate action: Consignment quarantined, QA notified within 2 hours, deviation DEV-2024-003 raised.
Disposition: Pending QA stability assessment; product not released.
CAPA: Mandatory 24-hour PCM conditioning checklist before loading; add GPS route alerts for cold chain trucks.
Status: CAPA in progress, target closure Q3 FY2024.

=== INCIDENT INC-2024-02 — SH-2024-007 REJECTION ===
Related shipment: SH-2024-007 | Product: TL-FROZ-7700 | Batch: BATCH-FRZ-2403
Event: Frozen biological consignment to SciLab Research Kolkata rose to -8°C, above the -10°C automatic rejection threshold.
Detection: Logger review on arrival, Apr 9.
Root cause: Insufficient dry ice loaded for a 2-day transit; dry ice fully sublimated before delivery.
Contributing factor: Vendor ArcticLine used a standard insulated case instead of the specified extended-duration case.
Immediate action: Full batch rejected automatically, destruction record DES-2024-007 raised, CDSCO notified within 72 hours.
Disposition: Destroyed per protocol; no product released.
CAPA: Dry ice quantity formula revised to 1.5x transit hours; mandatory extended-duration cases for transit over 24 hours; ArcticLine corrective action audit scheduled.
Status: CAPA open, vendor audit pending.

=== INCIDENT TREND ANALYSIS FY2024 ===
Both breaches involved temperature-sensitive products on multi-day transit.
Common theme: thermal packaging not matched to actual transit duration.
Breach rate fell within tolerance after CAPA rollout in the second half of the year.
Recommendation: Pre-shipment thermal validation for any cold chain or frozen route exceeding 24 hours.
"""

# ---------- Write all 5 files ----------
files = {
    "product_manual.txt":       product_manual,
    "compliance_guide.txt":     compliance_guide,
    "shipment_log.txt":         shipment_log,
    "vendor_list.txt":          vendor_list,
    "incident_report_2024.txt": incident_report,
}

written = 0
for fname, content in files.items():
    fpath = os.path.join(DOCS_PATH, fname)
    try:
        with open(fpath, "w", encoding="utf-8") as f:
            f.write(content.strip() + "\n")
        size_kb = os.path.getsize(fpath) / 1024
        print(f"✅ Wrote {fname:30s} ({size_kb:5.1f} KB)")
        written += 1
    except Exception as e:
        print(f"❌ Failed to write {fname}: {e}")

print("-" * 55)
print(f"📦 STATUS: {written}/5 documents written to Drive at {DOCS_PATH}")

# ==========================================================
# CELL 2 — SESSION SETUP: INSTALL LIBS + MOUNT DRIVE
# Run this first every new Colab session (Rule 1 + Rule 7).
# ==========================================================
import sys, subprocess

pkgs = [
    "chromadb", "sentence-transformers", "google-generativeai",  # ✅
    "langchain", "langchain-community", "pypdf",
    "streamlit", "pyngrok", "pandas", "langchain-text-splitters"
]
try:
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q", *pkgs],
        check=True
    )
    print("✅ Libraries installed successfully.")
    print("ℹ️  Any 'requests==2.32.4' / 'opentelemetry-sdk' warnings are harmless — ignore.")
except subprocess.CalledProcessError as e:
    print(f"❌ pip install failed: {e}")

# Mount Drive
from google.colab import drive
try:
    drive.mount('/content/drive', force_remount=False)
    print("✅ Google Drive mounted.")
except Exception as e:
    print(f"❌ Drive mount failed: {e}")

import os
BASE      = '/content/drive/MyDrive/RAG PROJECT'
DOCS_PATH = f'{BASE}/docs'
DB_PATH   = f'{BASE}/chroma_db'
APP_PATH  = f'{BASE}/app.py'

for p in (BASE, DOCS_PATH):
    print(("✅ Found " if os.path.isdir(p) else "⚠️  MISSING ") + p)
os.makedirs(DB_PATH, exist_ok=True)

print("-" * 55)
print(f"📦 STATUS: Session ready. BASE = {BASE}")

# ==========================================================
# CELL 3 — LOAD DOCUMENTS FROM DRIVE
# Builds: documents[] = [{text, source}, ...]
# ==========================================================
import os, glob

documents = []
try:
    txt_files = sorted(glob.glob(os.path.join(DOCS_PATH, "*.txt")))
    if not txt_files:
        raise FileNotFoundError(f"No .txt files in {DOCS_PATH}")
    for fpath in txt_files:
        with open(fpath, "r", encoding="utf-8") as f:
            text = f.read().strip()
        if text:
            documents.append({"text": text, "source": os.path.basename(fpath)})
            print(f"✅ Loaded {os.path.basename(fpath):30s} ({len(text):5d} chars)")
        else:
            print(f"⚠️  Skipped empty file: {os.path.basename(fpath)}")
except Exception as e:
    print(f"❌ Load failed: {e}")

print("-" * 55)
print(f"📦 STATUS: {len(documents)} documents loaded into documents[]")

# ============================================================
# CELL A — STRUCTURE-AWARE CHUNKING + RICH METADATA
# Splits on ==== headers first (keeps a product/section intact),
# only sub-splits sections longer than MAX_CHARS.
# Builds: chunks[], metadatas[], ids[]
# NOTE: keywords stored as comma-string (Chroma can't store lists).
# ============================================================

# If you get: ModuleNotFoundError: No module named 'langchain.text_splitter'
# run this once in a cell:  !pip install langchain-text-splitters

import re
from collections import Counter

# Version-safe import: new LangChain uses langchain_text_splitters,
# older versions use langchain.text_splitter
try:
    from langchain_text_splitters import RecursiveCharacterTextSplitter
except ModuleNotFoundError:
    from langchain.text_splitter import RecursiveCharacterTextSplitter

MAX_CHARS = 700        # sections above this get sub-split
OVERLAP   = 80

# Sub-splitter only used for oversized sections
sub_splitter = RecursiveCharacterTextSplitter(
    chunk_size=MAX_CHARS,
    chunk_overlap=OVERLAP,
    separators=["\n\n", "\n", ". ", " ", ""],
)

STOPWORDS = set("the a an and or to in for is are be an at by with from this that "
                "must mach any all not no if as per within within within product shipment".split())


def extract_keywords(text, k=6):
    words = re.findall(r"[a-z0-9\-]{3,}", text.lower())
    words = [w for w in words if w not in STOPWORDS]
    common = [w for w, _ in Counter(words).most_common(k)]
    return ", ".join(common)


def split_into_sections(text):
    """Split on ==== HEADER === markers, keeping header with its body."""
    parts = re.split(r"(?=^={3,}.*$)", text, flags=re.MULTILINE)
    return [p.strip() for p in parts if p.strip()]


def section_name_of(block):
    m = re.match(r"^={3,}\s*(.*?)\s*={3,}", block)
    return m.group(1).strip() if m else "GENERAL"


chunks, metadatas, ids = [], [], []

try:
    for doc in documents:
        src = doc["source"]
        doc_name = os.path.splitext(src)[0]
        sections = split_into_sections(doc["text"])

        # First pass: produce candidate chunks (section or sub-split)
        candidates = []  # (text, section_name)
        for sec in sections:
            sname = section_name_of(sec)
            if len(sec) <= MAX_CHARS:
                candidates.append((sec, sname))
            else:
                for piece in sub_splitter.split_text(sec):
                    candidates.append((piece.strip(), sname))

        total = len(candidates)
        for i, (ctext, sname) in enumerate(candidates):
            chunks.append(ctext)
            metadatas.append({
                "source": src,
                "doc_name": doc_name,
                "chunk_id": i,
                "chunk_total": total,
                "section_name": sname,
                "word_count": len(ctext.split()),
                "char_count": len(ctext),
                "keywords": extract_keywords(ctext),
            })
            ids.append(f"{src}_chunk_{i:03d}")
        print(f"  {src:30s} -> {total} chunks")

except Exception as e:
    print("❌ Chunking failed:", e)

print("-" * 55)
print(f"✅ STATUS: {len(chunks)} chunks ({total} total chunks built from {len(documents)} docs)")

# ==========================================================
# CELL 5 — LOAD MODEL, ENCODE CHUNKS, QUALITY CHECK
# Builds: model, embedding_list (list of 384-dim vectors)
# Prints encode time + similarity sanity check.
# ==========================================================
import time, numpy as np
from sentence_transformers import SentenceTransformer

model = None
embedding_list = []
try:
    t0 = time.time()
    model = SentenceTransformer('all-MiniLM-L6-v2')
    print(f"✅ Model loaded in {time.time()-t0:.1f}s (dim=384)")
except Exception as e:
    print(f"❌ Model load failed: {e}")

try:
    t0 = time.time()
    emb = model.encode(
        chunks, batch_size=32, show_progress_bar=True,
        normalize_embeddings=True   # so dot product == cosine
    )
    embedding_list = [v.tolist() for v in emb]
    dt = time.time() - t0
    rate = len(chunks) / dt if dt > 0 else 0
    print(f"✅ Encoded {len(chunks)} chunks in {dt:.1f}s ({rate:.1f} chunks/s)")
except Exception as e:
    print(f"❌ Encoding failed: {e}")

# ---- Quality check: query vs top chunks ----
try:
    emb_mat = np.array(embedding_list)
    test_q = "What temperature must TL-FROZ-7700 be stored at?"
    q_vec = model.encode([test_q], normalize_embeddings=True)[0]
    sims = emb_mat @ q_vec                       # cosine (vectors normalized)
    top = np.argsort(sims)[::-1][:3]
    print(f"\n🔎 Quality check — query: \"{test_q}\"")
    for rank, idx in enumerate(top, 1):
        preview = chunks[idx][:70].replace("\n", " ")
        print(f"   {rank}. {sims[idx]*100:5.1f}% | {metadatas[idx]['source']} | {preview}…")
except Exception as e:
    print(f"⚠️  Quality check skipped: {e}")

print("-" * 55)
print(f"📦 STATUS: {len(embedding_list)} embeddings ready (384-dim, normalized)")

# ==========================================================
# CELL 6 — DEDUPLICATE + STORE IN CHROMADB + VERIFY REPORT
# Collection: 'supply_chain' | cosine | persisted to Drive.
# ==========================================================
import time, hashlib, numpy as np
import chromadb

# ---------- 1. Deduplicate (exact text hash) ----------
seen, keep = set(), []
for i, c in enumerate(chunks):
    h = hashlib.md5(c.strip().lower().encode()).hexdigest()
    if h not in seen:
        seen.add(h); keep.append(i)
dupes = len(chunks) - len(keep)

chunks         = [chunks[i] for i in keep]
metadatas      = [metadatas[i] for i in keep]
ids            = [ids[i] for i in keep]
embedding_list = [embedding_list[i] for i in keep]
print(f"🧹 Deduplication: removed {dupes} duplicate chunk(s), {len(chunks)} remain")

# ---------- 2. Connect + fresh collection ----------
chroma_client = None
collection = None
try:
    chroma_client = chromadb.PersistentClient(path=DB_PATH)
    try:
        chroma_client.delete_collection("supply_chain")
        print("♻️  Old 'supply_chain' collection deleted.")
    except Exception:
        print("ℹ️  No existing collection to delete (fresh start).")
    collection = chroma_client.get_or_create_collection(
        name="supply_chain", metadata={"hnsw:space": "cosine"}
    )
    print("✅ Collection 'supply_chain' ready (cosine).")
except Exception as e:
    print(f"❌ ChromaDB connect failed: {e}")

# ---------- 3. Store in batches of 50 ----------
try:
    BATCH = 50
    t0 = time.time()
    for s in range(0, len(chunks), BATCH):
        e = s + BATCH
        collection.add(
            documents=chunks[s:e],
            embeddings=embedding_list[s:e],
            metadatas=metadatas[s:e],
            ids=ids[s:e],
        )
        print(f"   ➕ stored {min(e, len(chunks))}/{len(chunks)}")
    print(f"✅ Stored {collection.count()} chunks in {time.time()-t0:.1f}s")
except Exception as e:
    print(f"❌ Store failed: {e}")

# ---------- 4. Verification report ----------
try:
    print("\n" + "=" * 55)
    print("📋 VERIFICATION REPORT")
    print("=" * 55)
    per_doc = {}
    sizes = []
    for m in metadatas:
        per_doc[m["source"]] = per_doc.get(m["source"], 0) + 1
        sizes.append(m["char_count"])
    for src, n in sorted(per_doc.items()):
        print(f"   {src:30s} → {n} chunks")
    print(f"\n   Avg chunk size : {np.mean(sizes):.0f} chars")
    print(f"   Min / Max size : {min(sizes)} / {max(sizes)} chars")

    # Similarity distribution: each chunk vs its nearest neighbour
    emb_mat = np.array(embedding_list)
    sim = emb_mat @ emb_mat.T
    np.fill_diagonal(sim, -1)
    nn = sim.max(axis=1)
    print(f"\n   Nearest-neighbour cosine (chunk uniqueness):")
    print(f"     mean {nn.mean()*100:.1f}% | max {nn.max()*100:.1f}% | min {nn.min()*100:.1f}%")
    print(f"   (lower = more distinct chunks = healthier index)")
except Exception as e:
    print(f"⚠️  Report skipped: {e}")

print("-" * 55)
print(f"📦 STATUS: ChromaDB has {collection.count() if collection else 0} chunks at {DB_PATH}")

# ==========================================================
# CELL 7 — ADVANCED RETRIEVAL TEST (8 QUESTIONS)
# Pass = an expected keyword appears in any top-3 chunk.
# ==========================================================
import numpy as np

# question + keyword(s) that should appear in a relevant chunk
test_set = [
    ("What temperature must TL-COLD-9001 be stored at?",        ["2°c", "8°c"]),
    ("What is the shelf life of StableCap Dry Powder?",          ["36 months"]),
    ("How should TL-FROZ-7700 be transported?",                  ["dry ice"]),
    ("What happens if a frozen product rises above -10°C?",      ["rejected"]),
    ("Which shipment was quarantined and why?",                  ["sh-2024-003", "11.2"]),
    ("Who supplies the frozen biological product?",              ["arcticline"]),
    ("What was the root cause of incident INC-2024-02?",         ["dry ice", "sublimated"]),
    ("Within how many hours must CDSCO be notified of a recall?", ["72 hours"]),
]

TOP_K = 3
passes = 0
print("=" * 60)
print("🧪 ADVANCED RETRIEVAL TEST")
print("=" * 60)

for qi, (q, kws) in enumerate(test_set, 1):
    try:
        q_vec = model.encode([q], normalize_embeddings=True)[0].tolist()
        res = collection.query(query_embeddings=[q_vec], n_results=TOP_K)
        docs  = res["documents"][0]
        metas = res["metadatas"][0]
        dists = res["distances"][0]   # cosine distance

        hit = any(any(kw in d.lower() for kw in kws) for d in docs)
        if hit: passes += 1
        flag = "✅ PASS" if hit else "❌ FAIL"
        print(f"\nQ{qi} {flag} | {q}")
        for r, (d, m, dist) in enumerate(zip(docs, metas, dists), 1):
            sim = (1 - dist) * 100
            answer_here = "yes" if any(kw in d.lower() for kw in kws) else "no "
            preview = d[:60].replace("\n", " ")
            print(f"   {r}. {sim:5.1f}% | {m['source']:24s} | ans:{answer_here} | {preview}…")
    except Exception as e:
        print(f"\nQ{qi} ⚠️ error: {e}")

score = passes / len(test_set) * 100
print("\n" + "=" * 60)
print(f"📊 RETRIEVAL QUALITY SCORE: {passes}/{len(test_set)} = {score:.0f}%")
verdict = "🟢 Excellent" if score >= 87 else "🟡 Acceptable" if score >= 62 else "🔴 Needs tuning"
print(f"   Verdict: {verdict}")
print("-" * 60)
print(f"📦 STATUS: retrieval test complete ({score:.0f}% top-{TOP_K} hit rate)")

# ==========================================================
# CELL 8 — LOAD CROSS-ENCODER RERANKER
# CrossEncoder ships with sentence-transformers (already installed).
# Builds: reranker
# ==========================================================
from sentence_transformers import CrossEncoder

reranker = None
try:
    reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")
    print("✅ Cross-encoder loaded: ms-marco-MiniLM-L-6-v2")
except Exception as e:
    print(f"❌ Reranker load failed: {e}")

print("-" * 55)
print("📦 STATUS: reranker ready")

# ==========================================================
# CELL 9 — RETRIEVE + RERANK FUNCTION
# Stage 1: ChromaDB top-8 (bi-encoder recall)
# Stage 2: cross-encoder rerank → top-3 (precision)
# ==========================================================
def retrieve_and_rerank(question, fetch_k=8, top_n=3):
    """Returns list of dicts: {text, source, section, embed_score, rerank_score}."""
    try:
        q_vec = model.encode([question], normalize_embeddings=True)[0].tolist()
        res = collection.query(query_embeddings=[q_vec], n_results=fetch_k)
    except Exception as e:
        print(f"❌ Retrieval failed: {e}")
        return []

    docs  = res["documents"][0]
    metas = res["metadatas"][0]
    dists = res["distances"][0]
    if not docs:
        return []

    try:
        pairs  = [[question, d] for d in docs]
        scores = reranker.predict(pairs)
    except Exception as e:
        print(f"⚠️  Rerank failed, falling back to embed order: {e}")
        scores = [(1 - d) for d in dists]

    ranked = sorted(
        zip(docs, metas, dists, scores),
        key=lambda x: x[3], reverse=True
    )[:top_n]

    return [{
        "text": d,
        "source": m["source"],
        "section": m.get("section_name", "—"),
        "embed_score": round((1 - dist) * 100, 1),
        "rerank_score": round(float(s), 3),
    } for d, m, dist, s in ranked]

# ---- Demo ----
demo_q = "Why was shipment SH-2024-007 rejected?"
print(f"🔎 Demo query: {demo_q}\n")
for i, r in enumerate(retrieve_and_rerank(demo_q), 1):
    print(f"{i}. rerank={r['rerank_score']:+.2f} | embed={r['embed_score']}% | "
          f"{r['source']} [{r['section']}]")
    print(f"   {r['text'][:90].strip()}…\n")

print("-" * 55)
print("📦 STATUS: retrieve_and_rerank() ready for Day 3 Claude pipeline")

# ==========================================================
# CELL 10 — QUERY LOGGING SYSTEM (writes to Drive CSV)
# Builds: LOG_PATH, log_query()
# Day 3 will call log_query(...) after each Claude answer.
# ==========================================================
import os, csv
from datetime import datetime

LOG_PATH = f"{BASE}/query_logs.csv"
LOG_FIELDS = ["timestamp", "question", "sources", "scores",
              "answer", "response_time_s"]

def _ensure_log_file():
    if not os.path.exists(LOG_PATH):
        with open(LOG_PATH, "w", newline="", encoding="utf-8") as f:
            csv.writer(f).writerow(LOG_FIELDS)

def log_query(question, retrieved, answer, response_time_s):
    """retrieved = list of dicts from retrieve_and_rerank()."""
    try:
        _ensure_log_file()
        sources = " | ".join(r["source"] for r in retrieved)
        scores  = " | ".join(str(r.get("rerank_score", "")) for r in retrieved)
        row = [
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            question,
            sources,
            scores,
            answer.replace("\n", " ").strip(),
            round(response_time_s, 2),
        ]
        with open(LOG_PATH, "a", newline="", encoding="utf-8") as f:
            csv.writer(f).writerow(row)
        print(f"📝 Logged query ({response_time_s:.2f}s) → {os.path.basename(LOG_PATH)}")
        return True
    except Exception as e:
        print(f"❌ Logging failed: {e}")
        return False

# ---- Self-test with a fake entry (uses real retrieval, mock answer) ----
import time
_t0 = time.time()
_retrieved = retrieve_and_rerank("What is the shelf life of TL-DRY-4402?")
log_query(
    question="What is the shelf life of TL-DRY-4402?",
    retrieved=_retrieved,
    answer="StableCap Dry Powder (TL-DRY-4402) has a shelf life of 36 months.",
    response_time_s=time.time() - _t0,
)

print("-" * 55)
print(f"📦 STATUS: logging ready → {LOG_PATH}")

# ==========================================================
# CELL 10 — QUERY LOGGING SYSTEM (canonical schema, auto-migrating)
# Builds: LOG_PATH, LOG_FIELDS, log_query()
# Fix: ONE schema used by BOTH the Day 2 and Day 3 definitions,
#      so query_logs.csv never becomes corrupted/mixed.
# ==========================================================
import os, csv, shutil
from datetime import datetime

LOG_PATH = f"{BASE}/query_logs.csv"

# --- Single source of truth for the CSV schema (used everywhere) ---
LOG_FIELDS = [
    "timestamp",        # when the query ran
    "question",         # user question
    "answer",           # model answer (newlines flattened)
    "sources",          # unique source filenames, " | " separated
    "rerank_scores",    # rerank scores, " | " separated
    "num_chunks",       # number of chunks fed to the LLM
    "response_time_s",  # end-to-end latency in seconds
]


def _ensure_log_file():
    """Create the log file with the canonical header if it doesn't exist,
    and migrate/back up any old file whose header doesn't match."""
    if not os.path.exists(LOG_PATH):
        with open(LOG_PATH, "w", newline="", encoding="utf-8") as f:
            csv.writer(f).writerow(LOG_FIELDS)
        return

    # File exists — check its header matches the canonical schema.
    try:
        with open(LOG_PATH, "r", encoding="utf-8") as f:
            existing_header = next(csv.reader(f), [])
    except Exception:
        existing_header = []

    if existing_header != LOG_FIELDS:
        # Back up the incompatible file and start a clean, consistent one.
        backup = f"{LOG_PATH}.legacy_{datetime.now():%Y%m%d_%H%M%S}.bak"
        try:
            shutil.copy2(LOG_PATH, backup)
            print(f"♻️  Old log schema detected. Backed up to: {os.path.basename(backup)}")
        except Exception as e:
            print(f"⚠️  Could not back up old log ({e}); overwriting header anyway.")
        with open(LOG_PATH, "w", newline="", encoding="utf-8") as f:
            csv.writer(f).writerow(LOG_FIELDS)


def log_query(question, retrieved, answer, response_time_s):
    """Append one query record. `retrieved` = list of dicts from
    retrieve_and_rerank() (may be empty for I-don't-know answers)."""
    try:
        _ensure_log_file()
        retrieved = retrieved or []

        sources = " | ".join(sorted({r.get("source", "unknown") for r in retrieved}))
        scores  = " | ".join(str(r.get("rerank_score", "")) for r in retrieved)

        row = {
            "timestamp":       datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "question":        (question or "").strip(),
            "answer":          (answer or "").replace("\n", " ").strip(),
            "sources":         sources,
            "rerank_scores":   scores,
            "num_chunks":      len(retrieved),
            "response_time_s": round(float(response_time_s), 2),
        }

        with open(LOG_PATH, "a", newline="", encoding="utf-8") as f:
            csv.DictWriter(f, fieldnames=LOG_FIELDS).writerow(row)
        return True
    except Exception as e:
        print(f"❌ Logging failed: {e}")
        return False


# ---- Self-test: verify the function works WITHOUT polluting real data ----
# We write to a temp file, confirm it round-trips, then restore.
_real_log = LOG_PATH
try:
    LOG_PATH = f"{BASE}/_logtest_tmp.csv"
    if os.path.exists(LOG_PATH):
        os.remove(LOG_PATH)
    ok = log_query(
        question="SELF-TEST: shelf life of TL-DRY-4402?",
        retrieved=[{"source": "product_manual.txt", "rerank_score": 0.91}],
        answer="StableCap Dry Powder (TL-DRY-4402) shelf life is 36 months.",
        response_time_s=0.42,
    )
    import pandas as pd
    _df = pd.read_csv(LOG_PATH)
    assert list(_df.columns) == LOG_FIELDS, "schema mismatch"
    assert len(_df) == 1, "row not written"
    print("✅ Self-test passed — schema and write verified (real log untouched).")
    os.remove(LOG_PATH)
finally:
    LOG_PATH = _real_log  # restore canonical path

print("-" * 55)
print(f"📦 STATUS: logging ready (canonical schema) → {LOG_PATH}")

"""## Part 3"""

# ==============================================================
# CELL D3-1 — SESSION RESTORE
# Reload everything Day 2 left behind: libs, Drive, model,
# ChromaDB, reranker, retrieve_and_rerank(), log_query()
# ==============================================================

# --- Rule 1: pip libraries reset every session, always reinstall ---
!pip install chromadb sentence-transformers google-generativeai langchain langchain-community langchain-text-splitters pypdf streamlit pyngrok pandas -q

import os, time, csv
from datetime import datetime

# --- Rule 7: mount Drive before any file operation ---
from google.colab import drive
drive.mount('/content/drive', force_remount=False)
print('📂 Drive mounted')

# --- Path variables (never hardcode elsewhere) ---
BASE      = '/content/drive/MyDrive/RAG PROJECT'
DOCS_PATH = f'{BASE}/docs'
DB_PATH   = f'{BASE}/chroma_db'
APP_PATH  = f'{BASE}/app.py'
LOG_PATH  = f'{BASE}/query_logs.csv'
print('🗂️  Paths set')

# --- Reload embedding model (Rule 8) ---
from sentence_transformers import SentenceTransformer, CrossEncoder
model = SentenceTransformer('all-MiniLM-L6-v2')
print('🧠 Embedding model reloaded: all-MiniLM-L6-v2 (384-dim)')

# --- Reload ChromaDB from Drive (Rule 2, Rule 4, Rule 8) ---
import chromadb
try:
    chroma_client = chromadb.PersistentClient(path=DB_PATH)
    collection = chroma_client.get_or_create_collection(
        name='supply_chain',
        metadata={'hnsw:space': 'cosine'}
    )
    chunk_count = collection.count()
    print(f'💾 ChromaDB reloaded from Drive — collection "supply_chain" has {chunk_count} chunks')
except Exception as e:
    chunk_count = 0
    print(f'❌ ChromaDB load error: {e}')

# --- Reload reranker (Rule 8) ---
reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
print('🔀 Reranker reloaded: cross-encoder/ms-marco-MiniLM-L-6-v2')

# --- Redefine retrieve_and_rerank() exactly as Day 2 ---
def retrieve_and_rerank(query, retrieve_k=8, final_k=3):
    """Bi-encoder retrieval from ChromaDB, then cross-encoder rerank.
    Returns list of dicts: text, source, section, bi_sim, rerank_score."""
    try:
        q_emb = model.encode([query], normalize_embeddings=True).tolist()
        res = collection.query(
            query_embeddings=q_emb,
            n_results=retrieve_k,
            include=['documents', 'metadatas', 'distances']
        )
    except Exception as e:
        print(f'❌ ChromaDB query error: {e}')
        return []

    docs  = res.get('documents', [[]])[0]
    metas = res.get('metadatas', [[]])[0]
    dists = res.get('distances', [[]])[0]
    if not docs:
        return []

    # cosine distance -> similarity
    candidates = []
    for doc, meta, dist in zip(docs, metas, dists):
        candidates.append({
            'text': doc,
            'source': (meta or {}).get('source', 'unknown'),
            'section': (meta or {}).get('section', ''),
            'bi_sim': round(1.0 - float(dist), 4),
        })

    # cross-encoder rerank
    try:
        pairs = [[query, c['text']] for c in candidates]
        scores = reranker.predict(pairs)
        for c, s in zip(candidates, scores):
            c['rerank_score'] = round(float(s), 4)
        candidates.sort(key=lambda x: x['rerank_score'], reverse=True)
    except Exception as e:
        print(f'⚠️ Rerank error, falling back to bi-encoder order: {e}')
        for c in candidates:
            c.setdefault('rerank_score', c['bi_sim'])
        candidates.sort(key=lambda x: x['bi_sim'], reverse=True)

    return candidates[:final_k]

print('🔧 retrieve_and_rerank() redefined')

# --- Redefine log_query() exactly as Day 2 ---
def log_query(question, chunks, answer, response_time):
    """Append one query record to query_logs.csv on Drive."""
    try:
        file_exists = os.path.exists(LOG_PATH)
        sources = ', '.join(sorted({c.get('source', 'unknown') for c in chunks})) if chunks else ''
        rerank_scores = ', '.join(str(c.get('rerank_score', '')) for c in chunks) if chunks else ''
        row = {
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'question': question,
            'answer': answer,
            'sources': sources,
            'rerank_scores': rerank_scores,
            'num_chunks': len(chunks) if chunks else 0,
            'response_time': round(response_time, 3),
        }
        with open(LOG_PATH, 'a', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=list(row.keys()))
            if not file_exists:
                writer.writeheader()
            writer.writerow(row)
        return True
    except Exception as e:
        print(f'⚠️ log_query error: {e}')
        return False

print('📝 log_query() redefined')

# --- Finalize ---
SESSION_READY = True
print(f'\n✅ SESSION RESTORED — {chunk_count} chunks live, model + reranker + functions ready | SESSION_READY={SESSION_READY}')

from google.colab import userdata
userdata.get('gen-lang-client-0567562434')

# ============================================================
# CELL D3-2 — GEMINI API KEY SETUP AND VALIDATION  (FIXED)
# Load key from Colab Secrets, configure Gemini, live test call
# ============================================================

# Run once if needed:  !pip install -q -U google-generativeai

import os
import google.generativeai as genai

# --- Check session is ready ---
if 'SESSION_READY' not in globals() or not SESSION_READY:
    print('⚠ SESSION_READY not set — run CELL D3-1 first!')
else:
    print('✅ Session is ready')

# --- Rule 3: load GEMINI_API_KEY from Colab Secrets, fall back to getpass ---
SECRET_NAME = 'GEMINI_API_KEY'   # <-- must match your Colab secret name
API_KEY = None
try:
    from google.colab import userdata
    API_KEY = userdata.get(SECRET_NAME)
    if API_KEY:
        print(f'🔑 Loaded {SECRET_NAME} from Colab Secrets')
except Exception as e:
    print(f'⚠ Could not read Colab Secrets ({e})')

if not API_KEY:
    from getpass import getpass
    API_KEY = getpass('🔑 Enter your GEMINI_API_KEY (starts with AIza): ').strip()

# --- Set env var and configure ---
os.environ['GEMINI_API_KEY'] = API_KEY
genai.configure(api_key=API_KEY)

# --- Load model once and reuse ---
# FIX: gemini-1.5-flash is retired -> use a current model
MODEL_NAME = 'gemini-2.5-flash'
model_llm = genai.GenerativeModel(MODEL_NAME)

# --- Live test call ---
API_VALID = False
try:
    test_resp = model_llm.generate_content('Reply with exactly: OK')
    reply = test_resp.text.strip()
    print(f'💬 Gemini test reply: "{reply}"')
    API_VALID = True
except Exception as e:
    err = str(e).lower()
    if 'api key' in err or '401' in err or 'permission' in err:
        print('❌ Invalid API key')
    elif 'quota' in err or '429' in err:
        print('❌ Quota exceeded — wait and retry')
    elif '404' in err or 'not found' in err:
        print(f'❌ Model not found — run list_models() to pick another. ({e})')
    else:
        print(f'❌ Gemini error: {e}')

# --- Masked key + final status ---
masked = (API_KEY[:10] + '****') if API_KEY else 'NONE'
print(f'🔐 Key (masked): {masked}')
print(f'{"✅" if API_VALID else "❌"} GEMINI STATUS = API_VALID={API_VALID} | model={MODEL_NAME}')

# ==============================================================
# CELL D3-3 — BUILD query_rag() FUNCTION
# Retrieval -> grounded prompt -> Gemini -> log -> return
# Fixes:
#   * Correct error classification (429/quota checked BEFORE api-key)
#   * Retry with exponential backoff on rate limits (the real cause
#     of the previous "Invalid API key" red herring)
#   * Stronger error handling + a MEANINGFUL smoke test
# ==============================================================
import time, re

system_prompt = (
    "You are a supply chain Q&A assistant for TraceLink BioMed.\n"
    "Answer ONLY using the provided context from the company documents.\n"
    "If the answer is not present in the context, respond with exactly:\n"
    "'I don't have enough information in the provided documents to answer this question.'\n"
    "Do not use any outside knowledge. Be concise, factual, and professional."
)

IDK = "I don't have enough information in the provided documents to answer this question."


def _is_rate_limit(err_low):
    return any(k in err_low for k in ("429", "quota", "resource_exhausted", "rate limit", "rate_limit"))


def _is_auth_error(err_low):
    return any(k in err_low for k in ("401", "403", "api_key_invalid", "permission_denied", "unauthenticated"))


def _generate_with_retry(prompt, max_retries=4, verbose=True):
    last_exc = None
    for attempt in range(max_retries):
        try:
            return model_llm.generate_content(
                prompt,
                generation_config={"temperature": 0.1, "max_output_tokens": 512},
            )
        except Exception as e:
            last_exc = e
            err_low = str(e).lower()
            # Now also retry on dropped connections, not just 429s
            transient = (
                _is_rate_limit(err_low)
                or "connection reset" in err_low
                or "connection aborted" in err_low
                or "connectionreseterror" in err_low
            )
            if transient and attempt < max_retries - 1:
                wait = 5 * (2 ** attempt)  # 5, 10, 20, 40 seconds — much gentler
                if verbose:
                    print(f"⏳ Transient error. Retry {attempt + 1}/{max_retries - 1} in {wait}s...")
                time.sleep(wait)
                continue
            raise
    raise last_exc



def query_rag(question, retrieve_k=8, final_k=3, verbose=True):
    """Full RAG pipeline. Returns (answer, sources, chunks)."""
    t0 = time.time()

    if not question or not question.strip():
        return "Please enter a question.", [], []

    # Step 1: retrieve + rerank
    chunks = retrieve_and_rerank(question, retrieve_k, final_k)

    # Step 2: nothing retrieved -> refuse immediately
    if not chunks:
        rt = time.time() - t0
        log_query(question, [], IDK, rt)
        if verbose:
            print(f"❓ {question}\n💬 {IDK}\n📚 Sources: none\n⏱️ {rt:.2f}s")
        return IDK, [], []

    # Step 3-6: build grounded prompt
    context = "\n\n---\n\n".join(c["text"] for c in chunks)
    sources = sorted({c["source"] for c in chunks})
    user_message = f"Context:\n{context}\n\nQuestion: {question}"
    full_prompt = f"SYSTEM INSTRUCTIONS:\n{system_prompt}\n\nUSER MESSAGE:\n{user_message}"

    # Step 7-8: call Gemini (low temperature for grounded, deterministic answers)
    try:
        response = _generate_with_retry(full_prompt, verbose=verbose)
        answer = (response.text or "").strip()
        if not answer:
            answer = IDK
    except Exception as e:
        err = str(e).lower()
        # IMPORTANT: check rate-limit FIRST — Google's 429 messages often
        # also contain the words "api key", which previously caused a
        # misleading "Invalid API key" result.
        if _is_rate_limit(err):
            answer = "⚠️ Quota exceeded — wait and retry"
        elif _is_auth_error(err):
            answer = "⚠️ Invalid API key"
        else:
            answer = f"⚠️ Gemini error: {e}"
        sources, chunks = [], []  # don't cite sources for an error

    response_time = time.time() - t0
    log_query(question, chunks, answer, response_time)

    if verbose:
        print(f"❓ {question}")
        print(f"💬 {answer}")
        print(f"📚 Sources: {', '.join(sources) if sources else 'none'}")
        print(f"⏱️ {response_time:.2f}s")

    return answer, sources, chunks


print("🔧 query_rag() defined")

# --------------------------------------------------------------
# SMOKE TEST — meaningful, not "is the digit 2 present?"
# A pass requires: (a) sources returned, (b) the answer is not the
# refusal string, and (c) a real temperature range like "2°C to 8°C"
# / "2-8" / "2 to 8" appears.
# --------------------------------------------------------------
print("\n--- SMOKE TEST ---")
q = "What is the storage temperature for TL-COLD-9001?"
ans, srcs, used = query_rag(q, verbose=True)
ans_low = ans.lower()

# If we got an error response, surface it clearly instead of failing silently.
is_error = ans.startswith("⚠️")
if is_error:
    print(f"\n⚠️  Gemini call did not succeed: {ans}")
    print("   The pipeline logic is fine — this is an API/quota issue.")
    print("   Wait ~60s (free-tier per-minute limit) and re-run this cell.")

has_range   = bool(re.search(r"2\s*(°c)?\s*(to|-|–|—)\s*8", ans_low))
not_refused = ans.strip() != IDK
has_sources = len(srcs) > 0
grounded    = "product_manual.txt" in srcs

checks = {
    "answer not refused":            not_refused and not is_error,
    "temperature range 2–8 present": has_range,
    "sources returned":              has_sources,
    "grounded in product_manual":    grounded,
}
for name, ok in checks.items():
    print(f"   {'✅' if ok else '❌'} {name}")

passed = all(checks.values())
print(f"\n{'✅ PASS' if passed else '❌ FAIL'} — smoke test")
print(f"\n✅ CELL D3-3 done — query_rag() live, smoke test {'passed' if passed else 'FAILED'}")

import time

def quick_test_rag(question):
    """Quick helper to test the RAG pipeline."""
    print(f'Querying: {question}')
    try:
        # Ensure we are calling the main RAG function
        answer, sources, chunks = query_rag(question, verbose=True)
        return answer
    except NameError as e:
        return f'Error: {e}. Please ensure you have run CELL D3-1, D3-2, and D3-3 to define the RAG pipeline.'

# Example usage:
quick_test_rag('What is the storage temperature for TL-COLD-9001?')

# ==============================================================
# CELL D3-4 (QUOTA-LITE) — MINIMAL EVALUATION SUITE (3 questions)
# Reduced from 10 -> 3 requests to preserve daily Gemini quota for
# your live Streamlit demo. Same pacing + quota-aware classification.
#
# Set RUN_EVAL = False after it has passed once, so re-running the
# notebook top-to-bottom does NOT spend any Gemini requests here.
# ==============================================================
import time
from typing import List, Optional, Tuple, Dict, Any

import pandas as pd
from IPython.display import display

# ---- Master switch: flip to False to skip all live Gemini calls ----
RUN_EVAL = True

INTER_REQUEST_DELAY_S: float = 4.0     # spacing between calls (RPM safe)
QUOTA_MARKERS = ("429", "quota", "resource_exhausted", "rate limit", "rate_limit")
AUTH_MARKERS  = ("401", "403", "api_key_invalid", "permission_denied", "unauthenticated")

# Trimmed to 3 representative cases: one factual answer, one multi-doc
# answer, and the out-of-scope guardrail. (question, keywords, kind)
TESTS: List[Tuple[str, Optional[List[str]], str]] = [
    ("What is the storage temperature for TL-COLD-9001?",
        ["2", "8"], "answer"),
    ("Which shipments had temperature breaches in 2024?",
        ["sh-2024-003", "sh-2024-007"], "answer"),
    ("What is the capital of France?",
        None, "refuse"),
]


def _classify_error(answer_text: str) -> Optional[str]:
    low = answer_text.lower()
    if not answer_text.startswith("\u26a0") and "error" not in low and "quota" not in low:
        return None
    if any(m in low for m in QUOTA_MARKERS):
        return "quota"
    if any(m in low for m in AUTH_MARKERS):
        return "auth"
    if answer_text.startswith("\u26a0") or low.startswith("error"):
        return "error"
    return None


def _evaluate_one(index, question, keywords, kind) -> Dict[str, Any]:
    start = time.time()
    answer, sources, _used = query_rag(question, verbose=False)
    elapsed = time.time() - start

    answer_low = answer.lower()
    refused = answer.strip() == IDK
    err_kind = _classify_error(answer)

    if err_kind in ("quota", "auth", "error"):
        status, expected = "SKIP", "(model unavailable)"
    elif kind == "refuse":
        status = "PASS" if refused else "FAIL"
        expected = "(must refuse)"
    else:
        keyword_hit = bool(keywords) and any(k.lower() in answer_low for k in keywords)
        status = "PASS" if (keyword_hit and not refused) else "FAIL"
        expected = ", ".join(keywords) if keywords else ""

    return {
        "Q": f"Q{index}", "kind": kind, "status": status,
        "error_kind": err_kind or "", "latency_s": round(elapsed, 2),
        "sources": ", ".join(sources) if sources else "-",
        "question": question[:45], "expected": expected,
        "answer": answer[:70].replace("\n", " "),
    }


print("=" * 70)
print("EVALUATION SUITE (QUOTA-LITE) - 3 questions")
print(f"Pacing: {INTER_REQUEST_DELAY_S:.1f}s between requests")
print("=" * 70)

if not RUN_EVAL:
    print("\n⏭️  RUN_EVAL = False — skipping all live Gemini calls.")
    print("    No daily quota spent. Set RUN_EVAL = True to run the 3 tests.")
else:
    results: List[Dict[str, Any]] = []
    for i, (question, keywords, kind) in enumerate(TESTS, 1):
        row = _evaluate_one(i, question, keywords, kind)
        results.append(row)
        print(f"  {row['status']:4s} {row['Q']:3s} | {row['latency_s']:5.2f}s | {row['question']}")
        if i < len(TESTS):
            time.sleep(INTER_REQUEST_DELAY_S)

    results_df = pd.DataFrame(results)
    pd.set_option("display.max_colwidth", 75)
    print("\nResults table:")
    display(results_df[["Q", "kind", "status", "error_kind", "latency_s", "sources", "question"]])

    for row in results:
        print(f"\n[{row['status']}] {row['Q']} ({row['kind']}) | {row['latency_s']}s | {row['question']}")
        print(f"     expected: {row['expected']}")
        print(f"     answer  : {row['answer']}")
        print(f"     sources : {row['sources']}")

    # ---- Summary ----
    n_total = len(results)
    n_pass  = sum(1 for r in results if r["status"] == "PASS")
    n_fail  = sum(1 for r in results if r["status"] == "FAIL")
    n_skip  = sum(1 for r in results if r["status"] == "SKIP")
    quota_hits = sum(1 for r in results if r["error_kind"] == "quota")
    auth_hits  = sum(1 for r in results if r["error_kind"] == "auth")
    avg_latency = results_df["latency_s"].mean() if not results_df.empty else 0.0

    print("\n" + "=" * 70)
    print("SUMMARY")
    print(f"   Passed:             {n_pass}/{n_total}")
    print(f"   Failed:             {n_fail}/{n_total}")
    print(f"   Skipped (no model): {n_skip}/{n_total}")
    print(f"   Avg latency:        {avg_latency:.2f}s")
    print(f"   Gemini requests used this run: {n_total}")

    if quota_hits > 0:
        print("\n" + "-" * 70)
        print("DIAGNOSIS: Gemini quota limit reached (HTTP 429 / RESOURCE_EXHAUSTED).")
        print("   Per-minute limit: wait ~60s and re-run.")
        print("   Per-day limit:    resets at 00:00 Pacific, or switch to")
        print("                     gemini-2.5-flash-lite / enable billing.")
    elif auth_hits > 0:
        print("\n" + "-" * 70)
        print("DIAGNOSIS: Auth error (401/403). Re-run CELL D3-2 to reload your key.")

    evaluable = n_pass + n_fail
    if n_skip == n_total:
        verdict = "INCONCLUSIVE - model unavailable"
    elif evaluable > 0 and n_fail == 0:
        verdict = "Excellent" if n_skip == 0 else "Passing (some skipped due to quota)"
    elif evaluable > 0 and n_pass / evaluable >= 0.7:
        verdict = "Acceptable"
    else:
        verdict = "Needs tuning"
    print(f"\n   Verdict: {verdict}")
    print(f"\nCELL D3-4 done - {n_pass} passed, {n_fail} failed, {n_skip} skipped | {verdict}")

# ============================================================
# CELL D3-5 — DISPLAY QUERY LOG  (FIXED — robust CSV reading)
# Read query_logs.csv from Drive and summarize
# ============================================================

import pandas as pd
from IPython.display import display

EXPECTED_COLS = ['timestamp', 'question', 'sources', 'rerank_scores', 'response_time']

try:
    # Robust read: python engine handles quoting better; skip truly broken rows
    try:
        df = pd.read_csv(
            LOG_PATH,
            engine='python',
            on_bad_lines='skip',     # skip rows that can't be parsed
            quotechar='"',
            skipinitialspace=True,
        )
    except TypeError:
        # Older pandas uses error_bad_lines instead of on_bad_lines
        df = pd.read_csv(
            LOG_PATH,
            engine='python',
            error_bad_lines=False,
            quotechar='"',
            skipinitialspace=True,
        )

    total = len(df)

    # --- Build a display-friendly copy ---
    show = df.copy()
    if 'question' in show.columns:
        show['question'] = show['question'].astype(str).str.slice(0, 50)

    cols = [c for c in EXPECTED_COLS if c in show.columns]

    print(f'📄 Showing last 15 of {total} logged queries:\n')
    if cols:
        display(show[cols].tail(15))
    else:
        display(show.tail(15))   # fallback if headers differ

    avg_rt = df['response_time'].astype(float).mean() if 'response_time' in df.columns else 0.0
    print(f'\n📊 Total queries logged: {total}')
    print(f'⏱ Average response time: {avg_rt:.2f}s')
    print(f'\n✅ CELL D3-5 done — log read from {LOG_PATH}')

except FileNotFoundError:
    print(f'⚠ No log file yet at {LOG_PATH} — run some queries first.')
except Exception as e:
    print(f'❌ Error reading log: {e}')

# ==============================================================
# CELL D3-6 (CLINICAL PRECISION REDESIGN) — WRITE STREAMLIT APP TO DRIVE
# Design system: deep navy + electric blue, DM Sans, lifted cards,
# contrasting avatars, no emojis in UI, styled error cards, no debug info.
# Backend (retrieve_and_rerank + query_rag) = your exact pipeline.
# Launch with your existing CELL D3-7 — no changes needed.
# ==============================================================

app_code = r'''
import os
import streamlit as st
import chromadb
from sentence_transformers import SentenceTransformer, CrossEncoder
import google.generativeai as genai

# ---------------- CONFIG ----------------
BASE    = "/content/drive/MyDrive/RAG PROJECT"
DB_PATH = f"{BASE}/chroma_db"
LLM_MODEL_NAME = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")

COMPANY_NAME = "NexaChain BioMed"
TAGLINE      = "Intelligent Pharmaceutical Supply Chain"
DEMO_USER, DEMO_PASS = "demo", "demo123"

SYSTEM_PROMPT = (
    "You are Nova, an AI assistant for NexaChain BioMed.\n"
    "You only answer questions about pharmaceutical supply chain, cold chain "
    "logistics, product storage, shipments, vendors, regulatory compliance "
    "(WHO-GMP, FDA), and company operations.\n"
    "Answer ONLY using the provided context from the company documents.\n"
    "If the answer is not present in the context, say you can only assist with "
    "NexaChain BioMed supply-chain topics or that the information is not in the "
    "company documents.\n"
    "Do not use any outside knowledge. Be concise, factual, and professional."
)
OUT_OF_SCOPE = ("I can only assist with NexaChain BioMed supply-chain topics "
                "such as products, shipments, vendors, and compliance.")

# Page config — icon only in browser tab, never in UI
st.set_page_config(page_title=COMPANY_NAME, page_icon="\U0001F9EC",
                   layout="centered", initial_sidebar_state="collapsed")

# ---------------- DESIGN SYSTEM (CSS) — CLINICAL PRECISION ----------------
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap');

html, body, [class*="css"] { font-family:'DM Sans',sans-serif; }
.stApp { background:#F1F5F9; color:#334155; }
#MainMenu, footer, header {visibility:hidden;}
.block-container { padding-top:2rem; padding-bottom:2rem; max-width:900px; }

h1,h2,h3,h4 { color:#0A1628; font-weight:700; letter-spacing:-0.01em; }
h3 { font-size:1.4rem; }
p { font-size:0.92rem; }
.subtle { color:#94A3B8; font-size:0.82rem; line-height:1.55; }

/* Brand header */
.brand-row { display:flex; align-items:center; gap:.7rem; }
.brand-name { font-size:1.4rem; font-weight:700; color:#0A1628; }
.brand-tag  { color:#94A3B8; font-size:.82rem; margin-top:-.2rem; }

/* Decorative separator */
.rule { border:none; border-top:2px solid #2563EB; width:40px;
        margin:1.2rem auto 1.4rem auto; }

/* Cards */
.card { background:#FFFFFF; border:1px solid #E2E8F0; border-radius:16px;
        padding:1.4rem 1.5rem; height:100%; position:relative;
        box-shadow:0 2px 12px rgba(10,22,40,0.07);
        border-top:3px solid transparent;
        transition:box-shadow .18s ease, border-top-color .18s ease; }
.card:hover { box-shadow:0 8px 28px rgba(37,99,235,0.10);
        border-top:3px solid #2563EB; }
.card h4 { margin:0 0 .5rem 0; font-size:1.02rem; color:#0A1628; }
.card p  { margin:0; color:#94A3B8; font-size:.88rem; line-height:1.55; }

/* Login page background + card */
.login-card { background:#FFFFFF; border:1px solid #E2E8F0; border-radius:16px;
        padding:2.5rem; max-width:420px; margin:0 auto;
        box-shadow:0 8px 30px rgba(10,22,40,0.18); }
.login-header { text-align:center; margin-bottom:1.2rem; }
.login-header .brand-name { color:#FFFFFF; font-size:1.6rem; }
.login-header .brand-tag { color:#94A3B8; }

/* Buttons */
.stButton > button { background:#2563EB; color:#fff; border:none;
        border-radius:10px; padding:.6rem 1.5rem; font-weight:600;
        font-family:'DM Sans',sans-serif; transition:background .18s ease,
        box-shadow .18s ease; }
.stButton > button:hover { background:#1D4ED8; color:#fff;
        box-shadow:0 4px 14px rgba(37,99,235,0.25); }

/* Ghost button (secondary) */
.ghost .stButton > button { background:#FFFFFF; color:#334155;
        border:1px solid #E2E8F0; font-weight:500; }
.ghost .stButton > button:hover { background:#F8FAFC; color:#0A1628;
        border:1px solid #CBD5E1; box-shadow:none; }

/* Inputs (dark styled fields) */
.stTextInput > div > div > input,
.stTextArea textarea {
        background:#0A1628; color:#FFFFFF; border-radius:10px;
        border:1px solid #1E293B; }
.stTextInput > div > div > input:focus,
.stTextArea textarea:focus { outline:2px solid #2563EB; border:1px solid #2563EB; }
.stTextInput > div > div > input::placeholder { color:#94A3B8; }

/* Chat bubbles */
.chat-row { display:flex; align-items:flex-start; gap:.6rem; margin:.55rem 0; }
.chat-row.user { justify-content:flex-end; }
.avatar { width:36px; height:36px; border-radius:50%; flex:0 0 36px;
        display:flex; align-items:center; justify-content:center;
        color:#fff; font-weight:700; font-size:.9rem; }
.avatar.nova { background:#2563EB; }   /* electric blue */
.avatar.user { background:#DC2626; }   /* red */
.bubble { max-width:74%; padding:.7rem 1rem; font-size:.92rem; line-height:1.55; }
.bubble.nova { background:#FFFFFF; color:#334155; border:1px solid #E2E8F0;
        border-radius:18px 18px 18px 4px; }
.bubble.user { background:#0A1628; color:#fff;
        border-radius:18px 18px 4px 18px; }

/* Friendly error card */
.error-card { background:#FFFFFF; border:1px solid #FCA5A5;
        border-left:4px solid #DC2626; border-radius:12px;
        padding:.9rem 1.1rem; color:#334155; font-size:.9rem; }
.error-card b { color:#DC2626; }

/* Responsive: stack cards on small screens */
@media (max-width: 640px) {
    [data-testid="column"] { width:100% !important; flex:1 1 100% !important; }
    .card { margin-bottom:.9rem; }
    .login-card { padding:1.6rem; }
}
</style>
""", unsafe_allow_html=True)

# DNA / speech-bubble SVG icons (no emoji) — accent #2563EB
DNA_SVG = ('<svg width="26" height="26" viewBox="0 0 24 24" fill="none" '
           'stroke="#2563EB" stroke-width="2" stroke-linecap="round">'
           '<path d="M5 3c0 6 14 6 14 18M19 3c0 6-14 6-14 18"/>'
           '<path d="M7 6h10M7 18h10M9 9h6M9 15h6"/></svg>')
CHAT_SVG = ('<svg width="24" height="24" viewBox="0 0 24 24" fill="none" '
            'stroke="#2563EB" stroke-width="2" stroke-linecap="round" '
            'stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 '
            '2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>')

# ---------------- CACHED BACKEND (UNCHANGED LOGIC) ----------------
@st.cache_resource(show_spinner="Starting assistant...")
def load_resources():
    emb_model = SentenceTransformer("all-MiniLM-L6-v2")
    client = chromadb.PersistentClient(path=DB_PATH)
    coll = client.get_or_create_collection(
        name="supply_chain", metadata={"hnsw:space": "cosine"})
    rer = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")
    genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
    llm = genai.GenerativeModel(LLM_MODEL_NAME)
    return emb_model, coll, rer, llm

model, collection, reranker, model_llm = load_resources()

def retrieve_and_rerank(query, retrieve_k=8, final_k=3):
    try:
        q_emb = model.encode([query], normalize_embeddings=True).tolist()
        res = collection.query(query_embeddings=q_emb, n_results=retrieve_k,
                               include=["documents", "metadatas", "distances"])
    except Exception:
        return []
    docs  = res.get("documents", [[]])[0]
    metas = res.get("metadatas", [[]])[0]
    dists = res.get("distances", [[]])[0]
    if not docs:
        return []
    candidates = []
    for doc, meta, dist in zip(docs, metas, dists):
        candidates.append({"text": doc,
                           "source": (meta or {}).get("source", "unknown"),
                           "bi_sim": round(1.0 - float(dist), 4)})
    try:
        scores = reranker.predict([[query, c["text"]] for c in candidates])
        for c, s in zip(candidates, scores):
            c["rerank_score"] = round(float(s), 4)
        candidates.sort(key=lambda x: x["rerank_score"], reverse=True)
    except Exception:
        candidates.sort(key=lambda x: x["bi_sim"], reverse=True)
    return candidates[:final_k]

class NovaUnavailable(Exception):
    """Raised when the model call fails so the UI can show a styled card."""

def query_rag(question, retrieve_k=8, final_k=3):
    chunks = retrieve_and_rerank(question, retrieve_k, final_k)
    if not chunks:
        return OUT_OF_SCOPE
    context = "\n\n---\n\n".join(c["text"] for c in chunks)
    user_message = f"Context:\n{context}\n\nQuestion: {question}"
    full_prompt = f"SYSTEM INSTRUCTIONS:\n{SYSTEM_PROMPT}\n\nUSER MESSAGE:\n{user_message}"
    try:
        answer = (model_llm.generate_content(
            full_prompt,
            generation_config={"temperature": 0.1, "max_output_tokens": 512},
        ).text or "").strip()
        if not answer:
            raise NovaUnavailable()
        return answer
    except NovaUnavailable:
        raise
    except Exception:
        # Hide raw tracebacks — signal the UI to render a friendly error card
        raise NovaUnavailable()

# ---------------- SESSION STATE ----------------
ss = st.session_state
ss.setdefault("authenticated", False)
ss.setdefault("page", "home")
ss.setdefault("messages", [])
ss.setdefault("assistant_name", "Nova")
ss.setdefault("custom_instructions", "")
ss.setdefault("login_error", False)

# ===================== LOGIN PAGE =====================
def login_page():
    st.markdown(
        f"<div class='login-header'><div style='display:flex;align-items:center;"
        f"justify-content:center;gap:.6rem;'>{DNA_SVG}"
        f"<span class='brand-name'>{COMPANY_NAME}</span></div>"
        f"<p class='brand-tag'>{TAGLINE}</p></div>",
        unsafe_allow_html=True)
    st.write("")

    col = st.columns([1, 5, 1])[1]
    with col:
        st.markdown("<div class='login-card'>", unsafe_allow_html=True)
        st.markdown("#### Sign in to your workspace")
        u = st.text_input("Username", placeholder="Username",
                          label_visibility="collapsed")
        p = st.text_input("Password", type="password", placeholder="Password",
                          label_visibility="collapsed")
        if st.button("Sign In", use_container_width=True):
            if u == DEMO_USER and p == DEMO_PASS:
                ss.authenticated = True
                ss.login_error = False
                st.rerun()
            else:
                ss.login_error = True
        if ss.login_error:
            st.markdown("<div class='error-card'><b>Sign in failed.</b> "
                        "Invalid username or password.</div>",
                        unsafe_allow_html=True)
        st.markdown(f"<p class='subtle' style='margin-top:.8rem'>Demo access — "
                    f"username: <b>{DEMO_USER}</b> &middot; password: "
                    f"<b>{DEMO_PASS}</b></p>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

# ===================== HOME / DASHBOARD =====================
def home_page():
    top = st.columns([5, 1])
    with top[0]:
        st.markdown(f"<div class='brand-row'>{DNA_SVG}"
                    f"<span class='brand-name'>{COMPANY_NAME}</span></div>",
                    unsafe_allow_html=True)
        st.markdown(f"<p class='brand-tag'>{TAGLINE}</p>", unsafe_allow_html=True)
    with top[1]:
        st.markdown("<div class='ghost'>", unsafe_allow_html=True)
        if st.button("Sign Out"):
            ss.authenticated = False
            ss.page = "home"
            st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

    st.markdown("---")
    st.markdown("### Welcome back")
    st.markdown(f"<p class='subtle'>{COMPANY_NAME} delivers precision cold-chain "
                "and pharmaceutical logistics with full regulatory traceability. "
                "Our AI assistant gives your team instant, document-grounded "
                "answers on products, shipments, vendors, and compliance — "
                "available 24/7.</p>", unsafe_allow_html=True)
    st.markdown("<hr class='rule'>", unsafe_allow_html=True)

    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown("<div class='card'><h4>Cold Chain Monitoring</h4><p>End-to-end "
                    "temperature-controlled distribution with real-time sensor "
                    "monitoring and automated alerts.</p></div>",
                    unsafe_allow_html=True)
    with c2:
        st.markdown("<div class='card'><h4>Regulatory Compliance</h4><p>WHO-GMP "
                    "and FDA-aligned quality management at every step. Full audit "
                    "trail and document traceability.</p></div>",
                    unsafe_allow_html=True)
    with c3:
        st.markdown("<div class='card'><h4>AI-Powered Insights</h4><p>Instant "
                    "answers grounded in your verified company knowledge base. "
                    "Document-cited responses only.</p></div>",
                    unsafe_allow_html=True)

    st.write("")
    cta = st.columns([1, 1, 1])
    with cta[1]:
        if st.button(f"Chat with {ss.assistant_name}", use_container_width=True):
            ss.page = "chat"
            st.rerun()

    st.write("")
    with st.expander("Personalize your assistant"):
        name = st.text_input("Assistant name", value=ss.assistant_name)
        instr = st.text_area("Custom instructions (optional)",
                             value=ss.custom_instructions)
        if st.button("Save"):
            ss.assistant_name = name.strip() or "Nova"
            ss.custom_instructions = instr.strip()
            st.success(f"Saved. Assistant name set to {ss.assistant_name}.")
            st.rerun()

# ===================== CHAT PAGE =====================
def render_message(role, content):
    if role == "user":
        st.markdown(
            f"<div class='chat-row user'>"
            f"<div class='bubble user'>{content}</div>"
            f"<div class='avatar user'>U</div></div>",
            unsafe_allow_html=True)
    else:
        st.markdown(
            f"<div class='chat-row'>"
            f"<div class='avatar nova'>N</div>"
            f"<div class='bubble nova'>{content}</div></div>",
            unsafe_allow_html=True)

def chat_page():
    bot = ss.assistant_name
    top = st.columns([5, 1])
    with top[0]:
        st.markdown(f"<div class='brand-row'>{CHAT_SVG}"
                    f"<span class='brand-name'>{bot}</span></div>",
                    unsafe_allow_html=True)
        st.markdown(f"<p class='subtle'>Your {COMPANY_NAME} supply-chain "
                    "assistant. Answers are grounded in verified company "
                    "documents.</p>", unsafe_allow_html=True)
    with top[1]:
        st.markdown("<div class='ghost'>", unsafe_allow_html=True)
        if st.button("Back"):
            ss.page = "home"
            st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

    st.markdown("---")
    for msg in ss.messages:
        render_message(msg["role"], msg["content"])

    if prompt := st.chat_input(f"Ask {bot} about products, shipments, compliance..."):
        ss.messages.append({"role": "user", "content": prompt})
        render_message("user", prompt)
        with st.spinner("Thinking..."):
            try:
                answer = query_rag(prompt)
                ss.messages.append({"role": "assistant", "content": answer})
                render_message("assistant", answer)
            except NovaUnavailable:
                st.markdown(
                    f"<div class='error-card'><b>{bot} is currently unavailable.</b>"
                    " Please try again shortly.</div>",
                    unsafe_allow_html=True)

    st.write("")
    if ss.messages:
        st.markdown("<div class='ghost'>", unsafe_allow_html=True)
        if st.button("Clear conversation"):
            ss.messages = []
            st.rerun()
        st.markdown("</div>", unsafe_allow_html=True)

# ===================== ROUTER =====================
if not ss.authenticated:
    login_page()
elif ss.page == "chat":
    chat_page()
else:
    home_page()
'''

# --- Write to Drive ---
import os
try:
    with open(APP_PATH, 'w', encoding='utf-8') as f:
        f.write(app_code)
    print(f'app.py written to {APP_PATH}')
    print(f'File size: {os.path.getsize(APP_PATH)} bytes')
    print(f'Model: {os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")}')
    print('\nNow run your existing CELL D3-7 to launch via ngrok.')
except Exception as e:
    print(f'Failed to write app.py: {e}')

# ==============================================================
# CELL D3-7 (UPDATED) — LAUNCH PROFESSIONAL STREAMLIT VIA NGROK
# ==============================================================
from getpass import getpass
from pyngrok import ngrok
import os, time, socket, subprocess

PORT = 8501

print('ℹ️ Get a FREE ngrok token at: https://dashboard.ngrok.com/signup\n')

# --- Sanity checks ---
assert 'APP_PATH' in globals(), "❌ APP_PATH not defined — run CELL D3-6 first!"
assert os.path.exists(APP_PATH), f"❌ app.py missing at: {APP_PATH}"
print(f'✅ Found app file: {APP_PATH}')

if not os.environ.get('GEMINI_API_KEY'):
    raise RuntimeError('⚠️ GEMINI_API_KEY not set — re-run CELL D3-2 first!')
print('✅ GEMINI_API_KEY present')

# --- ngrok auth ---
ngrok_token = getpass('🔑 Enter your ngrok auth token: ').strip()
ngrok.set_auth_token(ngrok_token)

# --- Clean up old processes/tunnels ---
try:
    ngrok.kill()
except Exception:
    pass
get_ipython().system_raw('pkill -f streamlit || true')
time.sleep(2)

# --- Launch Streamlit in background ---
LOG = '/content/streamlit.log'
get_ipython().system_raw(
    f'streamlit run "{APP_PATH}" '
    f'--server.port {PORT} '
    f'--server.address 0.0.0.0 '
    f'--server.headless true '
    f'--server.enableCORS false '
    f'--server.enableXsrfProtection false '
    f'> {LOG} 2>&1 &'
)

# --- Wait for port ---
def port_open(port, host='127.0.0.1'):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(1)
        return s.connect_ex((host, port)) == 0

print('\n⏳ Waiting for Streamlit to start...')
started = False
for i in range(40):
    if port_open(PORT):
        started = True
        break
    time.sleep(1)

if not started:
    print('❌ Streamlit did NOT start. Last 40 log lines:\n')
    print(subprocess.run(['tail', '-n', '40', LOG],
                         capture_output=True, text=True).stdout)
    raise RuntimeError('Streamlit failed to start — fix error above, then re-run.')

print(f'✅ Streamlit listening on port {PORT}')

# --- Open tunnel ---
public_url = ngrok.connect(PORT, "http").public_url
print(f'\n🌍 PUBLIC URL → {public_url}')

print(f'''
✅ CELL D3-7 done — professional app launched.

👉 Click the PUBLIC URL above: {public_url}

📋 TEST CHECKLIST:
  ☐ Login page appears (try demo / demo123)
  ☐ Landing page shows NexaChain BioMed branding + feature cards
  ☐ "Personalize your assistant" lets you rename the chatbot
  ☐ "Chat with Nova" button opens the chat
  ☐ Ask: "What is the storage temperature for TL-COLD-9001?" → mentions 2C–8C
  ☐ Ask: "What is the capital of France?" → polite "don't know" response
  ☐ No dataset/chunk counts visible anywhere (hidden ✅)
  ☐ Sign out returns to login page
''')

